spring:
  application:
    name: bobfull-backend
  jackson:
    time-zone: Asia/Seoul

management:
  endpoint:
    prometheus:
      access: read-only
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
